version: "3.4"

x-default: &default
  build:
    context: .
    args:
      user: iwaseyusuke
  image: ryu-mininet
  tty: true
  privileged: true
  network_mode: "bridge"
  environment:
    - DISPLAY=${DISPLAY}
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /lib/modules:/lib/modules
    - ./app/ryu_opa_app.py:/root/ryu/ryu/app/ryu_opa_app.py
  restart: unless-stopped

services:

  node1:
    <<: *default
    container_name: node1

  node2:
    <<: *default
    container_name: node2

  node3:
    <<: *default
    container_name: node3
